### ISSUE TITLE
Release Process (LIVE) :green_circle: :honey_pot:

### ISSUE THREAD

**Issue by methylDragon** [colcon/colcon-hardware-acceleration#10] opened 2022-03-14 08:49 UTC
## Description
This issue tracks the status for the release of this repository into the `colcon` org and making it available for installation as `.deb` via the ROS 2 repositories.

It will detail the steps that need to be taken, and what recommended changes are good to have.

## Release Process
> **Note:** This process does not have to be followed if the package just needs to be installable by `pip`. Just do an independent release on PyPI in that case. However, note for [this reason](https://answers.ros.org/question/380279/bloom-an-ament_python-package-with-pip-dependencies/?answer=380305#post-id-380305), do not make the `pip` package a dependency for any packages meant to be built on the official ROS 2 buildfarm, since packages with `pip` dependencies cannot be built and released.
>
> If there is an intention for the package to be available for `.deb` installation, **do not do a PyPI release** and follow the following process instead, which will do the PyPI release for you alongside the `.deb` release.

### Steps
- [x] Create [`publish-python.yaml`](https://github.com/dirk-thomas/publish-python) file to define the release process
    - See example in [`colcon-core`](https://github.com/colcon/colcon-core/blob/master/publish-python.yaml)
- [x] Raise issue in [`colcon/colcon-core`](https://github.com/colcon/colcon-core) to request for this repo to be transferred into the `colcon` org (https://github.com/colcon/colcon-core/issues/493)
    - [x] Migrate package
- [x] `colcon` team to review package name and general approach
  - [x] Resolve their concerns: https://github.com/colcon/colcon-core/issues/493#issuecomment-1071350845
    - [x] Merge https://github.com/ros-acceleration/colcon-acceleration/pull/11
  - You can add tests in a test folder for copyright checks etc. referencing something like [this](https://github.com/colcon/colcon-installed-package-information)
- [x] Rename repo and package, remembering to change all internal name references
- [x] Change uses of "ROS" to "colcon" (e.g. ROS 2 workspace => colcon workspace) for docstrings, usage reminders, and README where appropriate. (Workspaces are not specific to ROS, they're all `colcon` workspaces!)
  - [x] Review and merge https://github.com/ros-acceleration/colcon-hardware-acceleration/pull/14
- [x] PR for implementation in the repo in that org to be sent and approved if necessary
- [x] Run [release](https://colcon.readthedocs.io/en/released/developer/release.html)
  - [x] For PyPI (@vmayoral to pass PyPI username to @methylDragon )
  - [x] For packagecloud (@vmayoral to pass packagecloud username to @methylDragon )

### Recommendations
- [ ] Implement the [tests](https://github.com/colcon/colcon-rerun/tree/main/test) for CI
  - Note that there will be an introduced issue with a [depreciation](https://docs.pytest.org/en/latest/deprecations.html#py-path-local-arguments-for-hooks-replaced-with-pathlib-path) with `pytest` separate and independent from this repo that should be fixed more generally
- [ ] Some comments erroneously call the workspaces ROS 2, when they're really `colcon` workspaces.

**Python notes**
- [ ] Would be good to get `flake8` passing on this
- [ ] Don't use `Popen` subshells/subshells unnecessarily, especially if it can be substituted with native Python invocations. It'll hide `stderr` printouts, and also slow things down. Examples:
  - [ ] All the instances where `cp` is called https://github.com/ros-acceleration/colcon-acceleration/search?q=cp can potentially be replaced with `shutil.copytree(dirs_exist_ok=True)` calls or similar
  - [ ] Calls to `mkdir` and `ls` can be replaced with the equivalent [pathlib calls](https://docs.python.org/3/library/pathlib.html#pathlib.Path.mkdir) and then filtered accordingly either using pathlib's glob signature, or something like `re`
- [ ] Use `os.getcwd()` instead of `pwd`, since `os.getcwd()` will be guaranteed to work across platforms (unless you deliberately want it to [resolve symlinks instead of getting the original path](https://vineetreddy.wordpress.com/2017/05/17/pwd-vs-getcwd/))
- [ ] It is extremely inefficient to be doing successive string increments ([example in repo (it's not the only file it happens in)](https://github.com/ros-acceleration/colcon-acceleration/blob/main/colcon_acceleration/subverb/emulation.py#L148)). This is **extremely inefficient** (~30x slower) because **EACH TIME** a string gets appended to, it does an entire **allocate a NEW memory buffer and copy the existing buffer and whatever is being added to it** operation. Please use [`.join()` instead](https://stackoverflow.com/questions/3055477/how-slow-is-pythons-string-concatenation-vs-str-join#:~:text=String%20join%20is%20significantly%20faster,a%20concatenation%20of%20the%20two).
  - [ ] This ALSO applies to chained `+` concatenates for the same reason! ([example in repo (it's not the only file it happens in)](https://github.com/ros-acceleration/colcon-acceleration/blob/main/colcon_acceleration/subverb/emulation.py#L526)) Every `+` is another reallocate and copy operation because Python unrolls the expression and does the adds incremently.

**Comment by vmayoral** [comment] 2022-03-24 08:26
@methylDragon I believe I've addressed the major concerns raised at https://github.com/colcon/colcon-core/issues/493 which should get us moving in here.

Currently the tools in here are well tested and known to work (and provided there're no glitches in future Vitis releases, they should remain as such). I like your recommendations above though, and believe this should be implemented but I'd like to prioritize the overall release process of hardware acceleration packages (tracked at https://github.com/ros2-gbp/ros2-gbp-github-org/pull/22#issuecomment-1073811491) before diving into these refinements, specially, because it'll need to be tested from a functionality perspective, which will take some additional time. 

For now, I've assigned you to the `Recommendations` item in that list so that if you have bandwidth, can help send PRs implementing them. If not, these recommendations should be implemented in future releases regardless.

**Comment by vmayoral** [comment] 2022-03-24 08:35
> - [ ] Create [publish-python.yaml](https://github.com/dirk-thomas/publish-python) file to define the release process

I believe https://github.com/ros-acceleration/colcon-acceleration/commit/6d4ddbaaee5e66d67743e8e299c35e3f547507b5 does it. Please assess @methylDragon.

**Comment by methylDragon** [comment] 2022-03-25 18:20
All the changes so far are good! The colcon team mentioned that, for the README, it would be good to specify **colcon workspace** instead of ROS workspace, since that's more technically correct and less ROS specific.

But this should only happen if the package can be used without ROS, which it looks like it can? Correct me if I'm wrong :o

**Comment by methylDragon** [comment] 2022-03-28 18:20
There's internal support for allowing the package release if the name is renamed to `colcon-hardware-acceleration`.

Remember to change the PRs, and the internal name references in any source files!

**Comment by vmayoral** [comment] 2022-03-29 11:14
@methylDragon https://github.com/colcon/colcon-core/issues/493#issuecomment-1081739573, let me know if we're good or I'm missing something.

**Comment by vmayoral** [comment] 2022-03-29 11:14
> Remember to change the PRs, and the internal name references in any source files!

I believe I picked all source changes, any additional action needed?

**Comment by methylDragon** [comment] 2022-03-29 17:30
There's some comments with ROS 2 instead of colcon, but I'm ok with them. I'll ping the team!

**Comment by vmayoral** [comment] 2022-03-29 17:33
> There's some comments with ROS 2 instead of colcon, but I'm ok with them. I'll ping the team!

Feel free to PR things out if I forget something please!

**Comment by methylDragon** [comment] 2022-03-29 17:40
Got it, though it might mean another release tag needs to be made, haha...

Let's see what the team thinks of using `acceleration` as a verb in the meantime.

**Comment by methylDragon** [comment] 2022-04-01 19:29
Hey @vmayoral , let me answer your query in a separate comment.

For now, for this repo, the acceleration colcon team has been created in https://github.com/colcon (you should accept the invite.)

Then, migrate this repo over there so we can proceed with the release, as per: https://github.com/colcon/colcon-core/issues/493

**Comment by methylDragon** [comment] 2022-04-01 19:42
> Accepted #14, created a new tag after changes and pushed appropriately to `rolling` and `humble` branches.
> 
> As a quick comment, from the documentation provided, my understanding is that the `main` branch should be maintained as the _release_ branch, is this correct @methylDragon? If so, should PRs like #14 be submitted against development branches like `rolling` (instead of to `main`)?
> 
> Let me know your thoughts about this so that I clarify it to the team internally. Thanks!

Specifically for `colcon` packages, there's no relation to ROS releases, so `rolling` and `humble` branches shouldn't exist for this repo.

As for the difference between `master` and `rolling`/`humble`/etc. branches for ROS 2 packages, I need to confirm internally, but my understanding is that master is for the next release, and the individual branches are for development AND release tagging **for the specific distro they are targeting**. So for each branch the source is separately maintained, though sometimes backports occur.

But I am only about 50-60% sure on this. If you take a look at the other packages out in the ecosystem, it's kind of a jungle. But my understanding seems to check out for `rclc` and `rclcpp` at least.

**Comment by methylDragon** [comment] 2022-04-01 21:13
Could I double check which documentation you are referring to?

**Comment by vmayoral** [comment] 2022-04-04 11:39
>Could I double check which documentation you are referring to?
>
>I might have accidentally phrased it vaguely, apologies for that :X

I had a quick look again and couldn't find the source of my assumption. Sorry. I've been going back and forth between older docs and your newly provided guidelines, so it might be somewhere there (or maybe I just simply misunderstood something). Regardless, thanks for clarifying things above!

I'll stick to the following for now since it seems the simplest approach (and the one I see in other colcon extensions):

> Specifically for colcon packages, there's no relation to ROS releases, so rolling and humble branches shouldn't exist for this repo.

With this clarified, I went ahead and migrated code to https://github.com/colcon/colcon-hardware-acceleration.

**Comment by vmayoral** [comment] 2022-04-04 11:48
Cathing up with https://github.com/colcon/colcon-core/issues/493#issuecomment-1086233533, and reacted accordingly deleting the newly created repo and transferring ownership as recommended. Will look now into the guidelines provided there as well.

**Comment by methylDragon** [comment] 2022-04-05 07:30
I've already created a packagecloud account, and I can use my existing PyPI to do the release. Let me give this one a try, I haven't done it before either :eyes:

**Comment by vmayoral** [comment] 2022-04-05 07:34
> I've already created a packagecloud account, and I can use my existing PyPI to do the release. Let me give this one a try, I haven't done it before either 👀

All right, I was just doing the same :) but I'll stop it and let you push it. For the sake of *human-transfer-learning*, do you think you could drop some notes on how the process went from your side 😄?

**Comment by methylDragon** [comment] 2022-04-05 07:36
No worries ;) I'm already writing internal notes. I'll pass them to you when done, though no promises on 100% accuracy or correctness..

**Comment by methylDragon** [comment] 2022-04-05 07:39
Oh, you might want to update the CHANGELOG. @vmayoral

**Comment by vmayoral** [comment] 2022-04-05 07:40
> Oh, you might want to update the CHANGELOG. @vmayoral

Will do.

Quick question, @nuclearsandwich suggested in https://github.com/colcon/colcon-core/issues/493#issuecomment-1086233533 to add more maintainers ([nuclearsandwich](https://pypi.org/user/nuclearsandwich/) in PyPI). Is this something we need to add to https://github.com/colcon/colcon-hardware-acceleration/blob/main/setup.cfg#L8-L11 or something you set within packagecloud?

**Comment by vmayoral** [comment] 2022-04-05 08:17
> Oh, you might want to update the CHANGELOG. @vmayoral

https://github.com/colcon/colcon-hardware-acceleration/pull/15

**Comment by methylDragon** [comment] 2022-04-05 10:17
Perfect timing. I was trying to run the releases and hit a small snag, and it's a perfect time to pass it on to you :eyes:

Since the `publish-python.yaml` specifies `ros-acceleration/colcon-hardware-acceleration` as the packagecloud repository, you'll need to do the release for that one. You need to make a packagecloud account specifically called `ros-acceleration`.

The PyPI package is up already. https://pypi.org/project/colcon-hardware-acceleration/0.6.1/
I'll add you as maintainer on the maintainer email listed on this package.

---

Then, follow these modified steps, augmenting the [[Release Guide](https://colcon.readthedocs.io/en/released/developer/release.html)](https://colcon.readthedocs.io/en/released/developer/release.html):

1. Install deps

```bash
curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
sudo apt update
sudo apt install gh

sudo apt install git ruby-full python3-yaml debhelper dh-python fakeroot python3-all
pip install wheel twine stdeb
pip install --upgrade requests

sudo gem install package_cloud
```

2. [Clone `publish-python`](https://github.com/dirk-thomas/publish-python)

Place the `bin` and `publish_python` directories in the root of the colcon package you want to release.

3. Configure authentication

```bash
# For PyPI
keyring set https://upload.pypi.org/legacy/ <username>

# Generate GPG key (use 4096 bits)
gpg --full-generate-key

# For packagecloud
# Get token from https://packagecloud.io/api_token and add it

# Configure gh
gh auth login
```

<aside>
💡 The packagecloud token needs to be placed in ~/.packagecloud

</aside>

4. Do the release
```
# Build the release artifacts (without uploading them)
./bin/publish-python

# Build and upload the release artifacts (to PyPI and Pakagecloud)
./bin/publish-python -upload

# Target a particular platform
# wheel:pypi, stdeb:packagecloud
./bin/publish-python -upload <TARGET>
```

5. Make PR
> In the case the Debian package is used by the ROS community you need to open a ticket in the GitHub repository [ros-infrastructure/reprepro-updater](https://github.com/ros-infrastructure/reprepro-updater/). The pull request should update the two files [colcon.ubuntu.upstream.yaml](https://github.com/ros-infrastructure/reprepro-updater/blob/master/config/colcon.ubuntu.upstream.yaml) and [colcon.debian.upstream.yaml](https://github.com/ros-infrastructure/reprepro-updater/blob/master/config/colcon.debian.upstream.yaml) file with a bumped version number for the package.

**Comment by methylDragon** [comment] 2022-04-05 10:18
Sorry, I can't add you on PyPI by email, pass me your PyPI account username instead!

**Comment by vmayoral** [comment] 2022-04-05 12:38
A few comments of my adventure for completeness following your indications @methylDragon:

<details><summary>:warning: Hurdle 1</summary>

```bash
xilinx@xilinx:~/ros2_ws/src/xilinx/colcon-hardware-acceleration$ ./bin/publish-python
...
dpkg-checkbuilddeps: error: Unmet build dependencies: python3-all debhelper (>= 9)
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    setup()
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/xilinx/.local/lib/python3.8/site-packages/stdeb/command/sdist_dsc.py", line 137, in run
    build_dsc(debinfo,
  File "/home/xilinx/.local/lib/python3.8/site-packages/stdeb/util.py", line 1569, in build_dsc
    dpkg_buildpackage(*args, cwd=fullpath_repackaged_dirname)
  File "/home/xilinx/.local/lib/python3.8/site-packages/stdeb/util.py", line 585, in dpkg_buildpackage
    process_command(args, cwd=cwd)
  File "/home/xilinx/.local/lib/python3.8/site-packages/stdeb/util.py", line 226, in process_command
    check_call(args, cwd=cwd)
  File "/home/xilinx/.local/lib/python3.8/site-packages/stdeb/util.py", line 59, in check_call
    raise CalledProcessError(retcode)
stdeb.util.CalledProcessError: 3
Traceback (most recent call last):
  File "./bin/publish-python", line 24, in <module>
    rc = main()
  File "/home/xilinx/ros2_ws/src/xilinx/colcon-hardware-acceleration/publish_python/cli.py", line 77, in main
    artifacts = artifact_handlers[artifact_type](config=artifact.config)
  File "/home/xilinx/ros2_ws/src/xilinx/colcon-hardware-acceleration/publish_python/artifact/stdeb.py", line 44, in create_deb
    subprocess.check_call(cmd, env=dict(os.environ, **add_env))
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'setup.py', '--command-packages=stdeb.command', 'sdist_dsc', '--source', 'python3-colcon-hardware-acceleration', '--with-python3', 'true', '--with-python2', 'false', '--force-x-python3-version', 'bdist_deb']' returned non-zero exit status 1.
```

Fixed by:

```bash
sudo apt-get install python3-all debhelper
```

</details>

<details><summary>:warning: Hurdle 2</summary>

```bash
xilinx@xilinx:~/ros2_ws/src/xilinx/colcon-hardware-acceleration$ ./bin/publish-python
...
 fakeroot debian/rules clean
dh clean --with python3 --buildsystem=python_distutils
dh: error: unable to load addon python3: Can't locate Debian/Debhelper/Sequence/python3.pm in @INC (you may need to install the Debian::Debhelper::Sequence::python3 module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at (eval 11) line 1.
BEGIN failed--compilation aborted at (eval 11) line 1.

make: *** [debian/rules:7: clean] Error 255
dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 2
Traceback (most recent call last):
...
```

Addressed by:

```bash
sudo apt-get install dh-python python3-distutils-extra
```

</details>

<details><summary>:warning: Hurdle 3</summary>

```bash
xilinx@xilinx:~/ros2_ws/src/xilinx/colcon-hardware-acceleration$ ./bin/publish-python --upload
...
== Uploading artifacts to 'pypi' ...
-- Uploading package to PyPI ...
$ twine upload -s dist/colcon-hardware-acceleration-0.7.0.tar.gz dist/colcon_hardware_acceleration-0.7.0-py3-none-any.whl
Traceback (most recent call last):
  File "/home/xilinx/.local/bin/twine", line 5, in <module>
    from twine.__main__ import main
  File "/home/xilinx/.local/lib/python3.8/site-packages/twine/__main__.py", line 22, in <module>
    from twine import cli
  File "/home/xilinx/.local/lib/python3.8/site-packages/twine/cli.py", line 20, in <module>
    import rich.highlighter
  File "/home/xilinx/.local/lib/python3.8/site-packages/rich/highlighter.py", line 5, in <module>
    from .text import Span, Text
  File "/home/xilinx/.local/lib/python3.8/site-packages/rich/text.py", line 5, in <module>
    from rich.emoji import EmojiVariant
  File "/home/xilinx/.local/lib/python3.8/site-packages/rich/emoji.py", line 4, in <module>
    from .jupyter import JupyterMixin
  File "/home/xilinx/.local/lib/python3.8/site-packages/rich/jupyter.py", line 4, in <module>
    from .segment import Segment
  File "/home/xilinx/.local/lib/python3.8/site-packages/rich/segment.py", line 19, in <module>
    from .cells import (
  File "/home/xilinx/.local/lib/python3.8/site-packages/rich/cells.py", line 6, in <module>
    from ._lru_cache import LRUCache
  File "/home/xilinx/.local/lib/python3.8/site-packages/rich/_lru_cache.py", line 8, in <module>
    from typing_extensions import OrderedDict
ImportError: cannot import name 'OrderedDict' from 'typing_extensions' (/usr/lib/python3/dist-packages/typing_extensions.py)
Traceback (most recent call last):
  File "./bin/publish-python", line 24, in <module>
    rc = main()
  File "/home/xilinx/ros2_ws/src/xilinx/colcon-hardware-acceleration/publish_python/cli.py", line 82, in main
    upload_handlers[upload_type](
  File "/home/xilinx/ros2_ws/src/xilinx/colcon-hardware-acceleration/publish_python/upload/pypi.py", line 16, in upload_pypi
    subprocess.check_call(cmd)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['twine', 'upload', '-s', 'dist/colcon-hardware-acceleration-0.7.0.tar.gz', 'dist/colcon_hardware_acceleration-0.7.0-py3-none-any.whl']' returned non-zero exit status 1.
```

Addressed by:
```bash
pip3 install typing_extensions --upgrade
```

</details>

<details><summary>:x: Hurdle 4</summary>

```bash
xilinx@xilinx:~/ros2_ws/src/xilinx/colcon-hardware-acceleration$ ./bin/publish-python --upload
...
== Uploading artifacts to 'pypi' ...
-- Uploading package to PyPI ...
$ twine upload -s dist/colcon-hardware-acceleration-0.7.0.tar.gz dist/colcon_hardware_acceleration-0.7.0-py3-none-any.whl
Traceback (most recent call last):
  File "/home/xilinx/.local/bin/twine", line 8, in <module>
    sys.exit(main())
  File "/home/xilinx/.local/lib/python3.8/site-packages/twine/__main__.py", line 33, in main
    error = cli.dispatch(sys.argv[1:])
  File "/home/xilinx/.local/lib/python3.8/site-packages/twine/cli.py", line 92, in dispatch
    registered_commands = importlib_metadata.entry_points(
  File "/home/xilinx/.local/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 1027, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/home/xilinx/.local/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 477, in load
    ordered = sorted(eps, key=by_group)
  File "/home/xilinx/.local/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 1024, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "/home/xilinx/.local/lib/python3.8/site-packages/importlib_metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
  File "/home/xilinx/.local/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 959, in _normalized_name
    return self._name_from_stem(stem) or super()._normalized_name
  File "/home/xilinx/.local/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 628, in _normalized_name
    return Prepared.normalize(self.name)
  File "/home/xilinx/.local/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 883, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
  File "/usr/lib/python3.8/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
Traceback (most recent call last):
  File "./bin/publish-python", line 24, in <module>
    rc = main()
  File "/home/xilinx/ros2_ws/src/xilinx/colcon-hardware-acceleration/publish_python/cli.py", line 82, in main
    upload_handlers[upload_type](
  File "/home/xilinx/ros2_ws/src/xilinx/colcon-hardware-acceleration/publish_python/upload/pypi.py", line 16, in upload_pypi
    subprocess.check_call(cmd)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['twine', 'upload', '-s', 'dist/colcon-hardware-acceleration-0.7.0.tar.gz', 'dist/colcon_hardware_acceleration-0.7.0-py3-none-any.whl']' returned non-zero exit status 1.
```

**Not addressed**.

</details>

I'm using an `Ubuntu 20.04` OS in my workstation with latest packages installed and updated (as of today). You guys may want to consider adding some of this to official documentation (and/or dockerizing the whole process). 

I stopped at `Hurdle 4` above and didn't continue further. @methylDragon feel free to provide support if necessary but given the hurdles, my suggestion would be to either :one: switch to https://github.com/colcon/colcon-hardware-acceleration/blob/main/publish-python.yaml#L9 and have someone with a working `publish-python` do it, or 2️⃣ provide support to make it work.

**Comment by methylDragon** [comment] 2022-04-05 17:55
Hey @vmayoral , could you double check if all the dependency steps I posted managed to run. At least for hurdles 1 and 2 the steps should have resolved them.

Regardless, the [PyPI package](https://pypi.org/project/colcon-hardware-acceleration/0.6.1/) is already up, and I'm still available if any updates need to be made.

For packagecloud, my mistake; let's wait on the main colcon packagecloud repo, though for now if you need either the public or internal teams to use `colcon-hardware-acceleration`, it should already be usable with `pip install colcon-hardware-acceleration`, since it's already on PyPI.

---

PS: Could you sign up for PyPI and pass me your username so I can add you in as an owner on the repo?

**Comment by vmayoral** [comment] 2022-04-06 07:56
> PS: Could you sign up for PyPI and pass me your username so I can add you in as an owner on the repo?

`ros-acceleration`

> Additionally: I think the colcon team wants to prepare to add you to the packagecloud org once they are able to, so you should also sign up for packagecloud and pass me your username for that too!

`ros-acceleration`

> Did you see the setup instructions in the [publish-python README](https://github.com/dirk-thomas/publish-python/)? I think at least 1 & 2 are covered by those setup instructions, which are linked to in the [release instructions](https://colcon.readthedocs.io/en/released/developer/release.html) although the link could be rephrased to indicate that the "details" include mandatory setup instructions. I'll take care of that.

Thanks @nuclearsandwich and @methylDragon, that indeed addresses 1 and 2. I was probably distracted. I went ahead an reproduced this again in a clean container and that worked just fine. Hurdles 3 and 4 above seem to be related to my workstation setup, so can be discarded safely.

<details><summary>Dockerfile</summary>

```dockerfile
FROM ros:rolling

# deps
RUN apt-get update && \
    apt-get upgrade -y --with-new-pkgs && \
    apt-get install -y \
      ccache \
      git \
      python3 \
      python3-pip \
      debhelper \
      dh-python \
      fakeroot \
      python3-all \
      python3-yaml \
      ruby-full \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install \
      wheel \
      twine \
      keyrings.alt \
      stdeb && \
    pip install --upgrade requests && \
    gem install package_cloud

RUN curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | \
        sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \
        | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null && \
    sudo apt update && sudo apt install gh

# setup publish-python and target repo
RUN git clone https://github.com/colcon/colcon-hardware-acceleration && \
    git clone https://github.com/dirk-thomas/publish-python && \
    cp -r publish-python/bin publish-python/publish_python colcon-hardware-acceleration

WORKDIR /colcon-hardware-acceleration

```

</details>

Let me know if you need anything else from my side.

**Comment by methylDragon** [comment] 2022-04-06 08:14
PyPI collaborator invite sent! I've added you as owner.

**Comment by vmayoral** [comment] 2022-04-06 08:22
> PyPI collaborator invite sent! I've added you as owner. @vmayoral

Accepted the invite. I'm in now! Thanks.

**Comment by nuclearsandwich** [comment] 2022-04-29 16:20
Thanks to @cottsay the 0.7.0 version of this package has been built and pushed to packagecloud, and from there is being imported into the ROS repositories via https://github.com/ros-infrastructure/reprepro-updater/pull/156

The package will be available in the ROS and ROS 2 repositories once those imports complete and the subsequent upload jobs are triggered which should be within the next few minutes.

@methylDragon, @vmayoral while direct access to packagecloud for the colcon-hardware-acceleration team is pending, please create new issues when you need packagecloud uploads for subsequent releases and assign myself and @cottsay.

**Comment by methylDragon** [comment] 2022-04-29 22:32
I see it on http://repo.ros2.org/status_page/rolling_default.html and http://repo.ros2.org/status_page/humble_default.html !! Thanks so much for the help! :birthday: :tada:

**Closed** 2022-05-31 12:55 UTC
